import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Check, Leaf, ShieldCheck, Sparkles, Activity } from 'lucide-react'
import { foods } from '../data/foods'
import { recipes } from '../data/recipes'
import FoodCard from '../components/FoodCard'
import RecipeCard from '../components/RecipeCard'

export default function Home() { return <>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="kicker"><span></span> Eat well, feel well</span><h1>Eat healthy.<br/><em>Live better.</em></h1><p>Discover delicious, nutritious food and simple healthy habits for a better lifestyle.</p><div className="hero-actions"><Link className="button" to="/foods">Explore healthy foods <ArrowRight size={17}/></Link><Link className="button button-ghost" to="/recipes">Discover recipes</Link></div><div className="hero-trust"><div className="avatar-stack"><span>LM</span><span>AK</span><span>JR</span></div><div><strong>4.9/5 from our community</strong><small>Join 12,000+ healthy food lovers</small></div></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=90" alt="Fresh healthy grain bowl with vegetables"/><div className="stat-float stat-top"><strong>100+</strong><span>healthy recipes</span></div><div className="stat-float stat-bottom"><span className="status-dot"></span><div><strong>Fresh & nutritious</strong><small>Good food, made simple</small></div></div></div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">A colorful start</span><h2>Good food is a daily ritual.</h2></div><Link className="text-button" to="/foods">Explore all foods <ArrowRight size={16}/></Link></div><div className="food-grid">{foods.slice(0,4).map((food) => <FoodCard key={food.id} food={food}/>)}</div></div></section>
  <section className="section section-tint"><div className="container"><div className="section-heading"><div><span className="eyebrow">Made for real life</span><h2>Recipes worth coming back to.</h2></div><Link className="text-button" to="/recipes">See all recipes <ArrowRight size={16}/></Link></div><div className="recipe-grid">{recipes.slice(0,3).map((recipe) => <RecipeCard key={recipe.id} recipe={recipe} favorite={false} onFavorite={() => {}}/>)}</div></div></section>
  <section className="section"><div className="container benefits"><div><span className="eyebrow">Why NutriBite</span><h2>Small choices.<br/><em>Big difference.</em></h2><p>We make healthy eating feel less like a rulebook and more like something you look forward to.</p><Link className="button" to="/nutrition">Explore nutrition <ArrowRight size={17}/></Link></div><div className="benefit-list"><Benefit icon={<Leaf/>} title="Nourish naturally" text="Thoughtful ingredients and approachable nutrition for every kind of day."/><Benefit icon={<Sparkles/>} title="Make it delicious" text="Flavor-first recipes that prove healthy food can be genuinely exciting."/><Benefit icon={<Activity/>} title="Build better habits" text="Simple tools that help you make progress without the pressure."/></div></div></section>
  <Newsletter/>
</> }
function Benefit({icon,title,text}) { return <div className="benefit"><div className="benefit-icon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div> }
function Newsletter() { const [email,setEmail]=useState(''); const [done,setDone]=useState(false); return <section className="newsletter"><div className="container newsletter-inner"><div><span className="eyebrow">The good stuff</span><h2>A healthier inbox,<br/>once a week.</h2></div><form onSubmit={(e)=>{e.preventDefault();if(email) setDone(true)}}>{done ? <p className="success"><Check size={18}/> You are on the list. Welcome in.</p> : <><p>Recipes, useful nutrition notes, and a little encouragement.</p><div className="newsletter-form"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address"/><button className="button" type="submit">Subscribe <ArrowRight size={16}/></button></div></>}</form></div></section> }
